# Generated by Django 5.1.7 on 2025-04-27 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
            ],
            options={
                'db_table': 'playlistdetail',
                'unique_together': {('playlist_id', 'track_id')},
            },
        ),
    ]
