# Generated by Django 5.1.7 on 2025-04-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user1_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='user2_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
    ]
