# Generated by Django 5.1.7 on 2025-04-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_sender_message_user1_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user1_messages', to='users.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user2_messages', to='users.user'),
        ),
    ]
