# Generated by Django 5.1.7 on 2025-04-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('popularity_score', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('gener', models.CharField(blank=True, max_length=255, null=True)),
                ('follower', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
    ]
