# Generated by Django 5.1.7 on 2025-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('popularity_score', models.IntegerField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('artist_img', models.CharField(max_length=200)),
                ('gener', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
    ]
