# Generated by Django 5.1.7 on 2025-05-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_img',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
