# Generated by Django 5.1.7 on 2025-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='popularity_score',
            field=models.IntegerField(),
        ),
    ]
