# Generated by Django 5.1.7 on 2025-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_img',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
