# Generated by Django 5.1.7 on 2025-04-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_artist_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='follower',
        ),
    ]
