# Generated by Django 5.1.7 on 2025-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_popularity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_img',
        ),
        migrations.AddField(
            model_name='artist',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='gener',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
    ]
