# Generated by Django 5.1.7 on 2025-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_image_url_alter_track_namemp3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='namemp3',
            field=models.CharField(max_length=255),
        ),
    ]
