# Generated by Django 5.1.7 on 2025-05-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_user1_id_alter_message_user2_id'),
        ('chat_message', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Chat_Message',
        ),
        migrations.RenameField(
            model_name='chat_message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
