# Generated by Django 5.1.7 on 2025-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('album_id', models.IntegerField(blank=True, null=True)),
                ('artist_id', models.IntegerField(blank=True, null=True)),
                ('is_copyright', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('mp3_filename', models.CharField(max_length=200)),
            ],
        ),
    ]
